#!/usr/bin/env bash
script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"

dry="0"

# if [ -z "$XDG_CONFIG_HOME" ]; then
#     echo "no xdg config hom"
#     echo "using ~/.config"
#     XDG_CONFIG_HOME=$HOME/.config
# fi
if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi


alias vim="nvim"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}


log "--------- dev-env ---------"

cd $script_dir
copy_dir() {
    pushd $1 > /dev/null
    to=$2
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    execute rm $to/$name     
    execute cp $from $to/$name
}



copy_dir  $DEV_ENV/.config $XDG_CONFIG_HOME
copy_dir  $DEV_ENV/.local $HOME/.local

copy_file $DEV_ENV/env/.zshrc $HOME
copy_file $DEV_ENV/env/.zsh_profile $HOME
